### ISSUE TITLE
node_modules\bindings\bindings.js:83 Uncaught Error: Module did not self-register.

### ISSUE THREAD

**Issue by justin-romano** [AtsushiSuzuki/node-clr#1]
I get this with windows 8.1
Any idea?

**Comment by AtsushiSuzuki** [comment]
Please let me know about your environment.
- node version
- visual studio version/edition.

Please try to uninstall and reinstall.
`npm remove clr`
`npm install clr`
If any error occurs, tell me about the error messages.

**Comment by justin-romano** [comment]
no ok. This works ok.
I was using NWJS but this all works fine in a normal node app.
