### ISSUE TITLE
Unable to build against node v14.15.1

### ISSUE THREAD

**Issue by Guevara-chan** [AtsushiSuzuki/node-clr#16]
Compilation just fails with:
```
npm WARN notsup Unsupported engine for clr@0.0.18: wanted: {"node":">=0.12 <8"} (current: {"node":"14.15.1","npm":"6.14.
8"})
npm WARN notsup Not compatible with your version of node/npm: clr@0.0.18
```

**Comment by AtsushiSuzuki** [comment]
I just published 0.0.19, with node 1.15.4.
This project is almost abandoned so you'd better find some alternatives, like edge.js.

**Comment by Guevara-chan** [comment]
You know, I have actual project built against your lib. It's almost abandoned itself, sure, but `Edge.js` does not suffice for it.

**Comment by Guevara-chan** [comment]
That being said, looks like we got new problem here:
`LINK : fatal error LNK1104: не удается открыть файл "MSCOREE.lib" [C:\Users\Guevara-han\AppData\Roaming\npm\node_modules\clr\build\clr.vcxproj]`

**Comment by AtsushiSuzuki** [comment]
It seems that you are missing .NET Framework or C++/CLI. Try install that
with VC++ Build Tools.

2020年12月21日(月) 21:33 Victoria Guevara <notifications@github.com>:

**Comment by Guevara-chan** [comment]
No. Actually, it's https://dotnet.microsoft.com/download/dotnet-framework/thank-you/net472-developer-pack-offline-installer that I was missing. Fixed now, thanks.
