### ISSUE TITLE
STAThread attribute support.

### ISSUE THREAD

**Issue by Guevara-chan** [AtsushiSuzuki/node-clr#2]
It seems that in current state clr module does not support clipboard nor file dialogs, since they do require specific thread attribute. Is there any way to fix that ?

**Comment by AtsushiSuzuki** [comment]
Long before, when I tried to fix this, `System.Threading.Thread.SetApartmentState` didn't work.
I wonder there is any way to set apartment state of existing thread.

**Comment by Guevara-chan** [comment]
For some reason it works with [tint2](https://github.com/trueinteractions/tint2)'s API bridge. Could you, like, investigate their source codes ?

**Comment by AtsushiSuzuki** [comment]
Interesting.
tint2 looks like modified node runtime.
On the other hand, node-clr is node module so node-clr does not have control of node's main loop thread.

In 0.0.15, node-clr sets apartment state of node's main thread at DllMain.
I don't think this is very reliable (any other module can set apartment state before this),
I have confirmed System.Windows.Forms.OpenFileDialog works. (see examples/openfile.js)
