### ISSUE TITLE
Event arguments not being passed correctly.

### ISSUE THREAD

**Issue by Guevara-chan** [AtsushiSuzuki/node-clr#7]
Consider following code, modified straight from GUI sample:

```
require('clr').init({ assemblies: [ 'System.Windows.Forms' ] });
with (System.Windows.Forms) {
var f = new Form();
   
var p = new FlowLayoutPanel();
f.Controls.Add(p);
   
var t = new TextBox();
t.Text = 'world';
p.Controls.Add(t);
   
var b = new Button();
b.Text = 'Greet';
b.Click.add(function (thiz, ea) {
console.log('clicked');
MessageBox.Show('Hello, ' + thiz.Text + '!');
});

p.Controls.Add(b);
Application.Run(f);
}
```

As you can guess, it was supposed to output "Hello, Greet !", but in reality results will be just like that:

![image](https://cloud.githubusercontent.com/assets/8768470/25100648/8f2d4844-23b9-11e7-970e-6be4ff4619eb.png)

Why so ? Mostly because both `thiz` and `ea` was passed as empty objects (`{}`), according to inspector.

**Comment by AtsushiSuzuki** [comment]
seems that there is a bug in object marshaling, .NET objects as node function argument do not correctly marshaled to node object.

**Comment by AtsushiSuzuki** [comment]
clr 0.0.17 released.
This bug is fixed for this case (javascript function as event handler), but still exists for other cases. (javascript function as callback function)

**Comment by Guevara-chan** [comment]
Is it only me, or problem still wasn't resolved even for event handling ? Found no difference with 0.0.17 for my sample.

**Comment by AtsushiSuzuki** [comment]
With 0.0.17, your sample seems to work as expected.

**Comment by Guevara-chan** [comment]
Ah, my bad. Seems like npm failed to update packages correctly. Everything works now.
